version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - app  # needs to wait for the backend to be ready
  app:
    build: ./server
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db # needs to wait for the database to be ready
    environment: # all env vars are red from .env file in the root directory
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data # persist data even if container shuts down
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  db_data: